# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce30a45f4b1dd5d7c24fff3a89a0e9220c6452b122197197c40933be9bfa57f775abdef45caf0ba6ea3bdfc28c9049053f9770932ea64d80904457cbcaa374e7

test:
  secret_key_base: b468d5522a53fc46dde57a3d18f2d77d6dfe8842bc435b5a0bd593ac4ac6719a2d8c99b478c403930a795065d8eae7dcfb116a326494b74b9cef74b6c514045c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
